#!/bin/bash

##Узнаём имя микротика нового клиента
echo -e "\nВведите имя микротика (например, mt-lpm)\n"
read Mt_name

##Создаём пароль и сохраняем его в переменную
Mt_password=$(apg -x 10 -M CSN -n 1) 
echo -e "\nMikrotik Radius/OpenVPN password for WNAM is" $Mt_password "\n"

#Настраиваем OpenVPN
##Добавляем в /etc/openvpn/user.pass логопасс
echo $Mt_name":"$Mt_password >> /etc/openvpn/user.pass
echo -e "Логопасс для OpenVPN сохранён\n"
##Выдаём туннельный IP микротику
###Находим все тунненльные IP и демонстрируем последние два
echo Последние туннельные IP-адреса:
cat /etc/openvpn/ipp.txt | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" | tail -2
###Определяем следующий по порядку IP
openvpn_last_octet=$(cat /etc/openvpn/ipp.txt | tail -1 | awk -F '\\.' '{print $NF}')
openvpn_next_octet=$(($openvpn_last_octet + 6)) #OpenVPN при первом вводе IP воспринимает его с маской /30, при перезагрузке сервиса отобразится корректный IP площадки

echo Следующий туннельный IP-адрес
if [ $openvpn_next_octet -gt 255 ]
then 
echo "Некорректный вид IP-адреса, задайте его вручную"
else 
openvpn_next_ip= echo $(cat /etc/openvpn/ipp.txt | tail -1 | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" | awk -F '\\.' '{print $1"."$2"."$3"."}')$openvpn_last_octet
echo $openvpn_next_ip
echo $Mt_name":"$openvpn_next_ip >> /etc/openvpn/ipp.txt

